name: PyTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
   runs-on: ubuntu-latest
   steps:
    - name: Clonar Repositorio
      uses: actions/checkout@v4

    - name: Instalar Python
      uses: actions/setup-python@v5
      with:
       python-version: '3.11'

    - name: Instalar Dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Correr los tests con PyTest
      run: |
        pytest --maxfail=1 --disable-warnings -q
